apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawbridge
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: ghcr.io/profianinc/drawbridge:0.2.0-rc2
        name: drawbridge
