apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawbridge
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: ghcr.io/profianinc/drawbridge@sha256:abcdefg
        name: drawbridge
