apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: store
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: drawbridge-staging
  storageClassName: azureblob-fuse-premium
